import { pgTable, serial, text, timestamp, integer, numeric, jsonb } from 'drizzle-orm/pg-core';

export const users = pgTable('users', {
  id: serial('id').primaryKey(),
  email: text('email').notNull().unique(),
  passwordHash: text('password_hash').notNull(),
  name: text('name').notNull(),
  role: text('role').notNull().default('viewer'),
  createdAt: timestamp('created_at').defaultNow(),
});

export const crawlCandidates = pgTable('crawl_candidates', {
  id: serial('id').primaryKey(),
  title: text('title').notNull(),
  sourceUrl: text('source_url'),
  sourcePlatform: text('source_platform'),
  city: text('city'),
  state: text('state'),
  neighborhood: text('neighborhood'),
  date: text('date'),
  timeStart: text('time_start'),
  timeEnd: text('time_end'),
  price: text('price'),
  organizerName: text('organizer_name'),
  ticketUrl: text('ticket_url'),
  imageUrl: text('image_url'),
  description: text('description'),
  stops: integer('stops'),
  includes: text('includes'),
  confidence: integer('confidence'),
  status: text('status').notNull().default('pending'),
  wpPostId: integer('wp_post_id'),
  duplicateOfId: integer('duplicate_of_id'),
  internalScore: integer('internal_score'),
  bottleCaps: numeric('bottle_caps'),
  scoreInputs: jsonb('score_inputs'),
  notes: text('notes'),
  reviewedBy: integer('reviewed_by'),
  reviewedAt: timestamp('reviewed_at'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const venueCandidates = pgTable('venue_candidates', {
  id: serial('id').primaryKey(),
  name: text('name').notNull(),
  address: text('address'),
  city: text('city'),
  state: text('state'),
  neighborhood: text('neighborhood'),
  phone: text('phone'),
  website: text('website'),
  googlePlaceId: text('google_place_id'),
  rating: numeric('rating'),
  reviewCount: integer('review_count'),
  priceLevel: integer('price_level'),
  hours: jsonb('hours'),
  photoUrl: text('photo_url'),
  menuUrl: text('menu_url'),
  types: text('types'),
  latitude: numeric('latitude'),
  longitude: numeric('longitude'),
  status: text('status').notNull().default('pending'),
  wpPostId: integer('wp_post_id'),
  duplicateOfId: integer('duplicate_of_id'),
  createdAt: timestamp('created_at').defaultNow(),
});

export const organizers = pgTable('organizers', {
  id: serial('id').primaryKey(),
  name: text('name').notNull(),
  email: text('email'),
  phone: text('phone'),
  website: text('website'),
  logoUrl: text('logo_url'),
  bio: text('bio'),
  claimStatus: text('claim_status').notNull().default('unclaimed'),
  outreachStatus: text('outreach_status').default('none'),
  outreachNotes: text('outreach_notes'),
  wpPostId: integer('wp_post_id'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const auditLog = pgTable('audit_log', {
  id: serial('id').primaryKey(),
  userId: integer('user_id'),
  action: text('action').notNull(),
  entityType: text('entity_type'),
  entityId: integer('entity_id'),
  details: jsonb('details'),
  createdAt: timestamp('created_at').defaultNow(),
});
